### ISSUE TITLE
missing dataset

### ISSUE THREAD

**Issue by mkhairy** [wenischlab/MicroSuite#5]
In the dataset directory you uploaded here (https://akshithasriraman.eecs.umich.edu/dataset/), there are still missing files such as:
~/MicroSuite/datasets/Recommend/query_set.csv
~/MicroSuite/datasets/SetAlgebra/query_set.txt
~/MicroSuite/datasets/Recommend/query_set.csv
and the tar file used in SetAlgerba (Wikipedia file), you said in the readme tutorial "(the available tar file must first be extracted on your machine)" but I cannot find that tar file in the directory

Thanks!

**Comment by akshithasriraman** [comment]
1. Please note the instruction in the README that states that you must create corresponding files for "query_set.txt" by stripping away a part of the data set as is applicable to your needs - _"Test sets for the load generator can be created as large as you want them to be by stripping away a part of the data set."_
2. You don't need to extract the tar, because the entire WordIDs mapping file that the README lists is already present in the dataset directory under Set Algebra.
